Trad carol
appliedepi/epirhandbook_pt pull request #13
Opened 2021-12-16 20:44 UTC by cmusso86

tradução Carol, Lais e Rafaela

2022-05-07 20:24 UTC, halian-vilela requested changes

2022-05-07 20:37 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +A sintaxe é significativamente diferente dos gráficos gerados pelo R **base***, e tem uma curva de aprendizado associada a ela. A utilização do **ggplot2** geralmente exige que o usuário formate seus
A sintaxe é significativamente diferente dos gráficos gerados pelo R **base***, e tem uma curva de aprendizado associada a ela. A utilização do **ggplot2** geralmente exige que o usuário formate seus dados de uma forma altamente **compatível com o "tidyverse"**, o que em última análise torna a utilização conjunta destes pacotes muito eficaz.

2022-05-07 20:39 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +A sintaxe é significativamente diferente dos gráficos gerados pelo R **base***, e tem uma curva de aprendizado associada a ela. A utilização do **ggplot2** geralmente exige que o usuário formate seus
```suggestion
A sintaxe é significativamente diferente dos gráficos gerados pelo R **base***, e tem uma curva de aprendizado associada a ela. A utilização do **ggplot2** geralmente exige que o usuário formate seus dados de uma forma altamente **compatível com o "tidyverse"**, o que em última análise torna a utilização conjunta destes pacotes muito eficaz.

```

2022-05-09 01:17 UTC, halian-vilela requested changes
Fui até a linha 300, amanhã faço mais.

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +A alternativa é mapear os argumentos da estética de um gráfico a uma coluna (variável) do seus dados. Nesta abordagem, a exibição deste *aesthetics* dependerá do valor desta observação naquela coluna
```suggestion
A alternativa é mapear os argumentos da estética de um gráfico a uma coluna (variável) do seus dados. Nesta abordagem, a exibição deste *aesthetics* dependerá do valor desta observação naquela coluna dos dados. Se os valores da coluna forem contínuos, a escala de exibição (legenda) para aquele *aesthetics* será contínua. Se os valores da coluna forem discretos, a legenda exibirá cada valor e os dados plotados aparecerão "agrupados" de forma distinta (leia mais na seção [agrupamento](#ggplotgroups) desta página).  

```

A ideia do "distinctly" aqui é mais ao pé da letra mesmo... o sentido é dizer que o agrupamento será feito de forma a criar uma "distinção" entre os grupos de dados.

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +* No segundo exemplo, duas novas *aesthetics* do gráfico também são mapeados para colunas (`color = ` e `size = `), enquanto a *aesthetics* do gráfico `shape = ` e `alpha = ` são mapeados para valore
```suggestion
* No segundo exemplo, duas novas *aesthetics* do gráfico também são mapeados para colunas (`color = ` e `size = `), enquanto a *aesthetics* do gráfico `shape = ` e `alpha = ` são mapeados para valores estáticos fora de qualquer função `mapping = aes()`.   

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         x = age,           # mapeie o eixo x pata idade (coluna age)
```suggestion
         x = age,           # mapeie o eixo x para idade (coluna age)       

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         y = wt_kg,         # mapeie o eixo y pata peso (wt_kg)
```suggestion
         y = wt_kg,         # mapeie o eixo y para peso (wt_kg)      

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         color = age) # mapeie a cor segundo a iddade
```suggestion
         color = age) # mapeie a cor segundo a idade

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         x = age,           # mapeie o eixo x pata idade (coluna age)
```suggestion
         x = age,           # mapeie o eixo x para idade (coluna age)    

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         y = wt_kg,         # mapeie o eixo y pata peso (wt_kg)
```suggestion
         y = wt_kg,         # mapeie o eixo y para peso (wt_kg) 

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         color = age,       # mapeie a cor segundo a iddade
```suggestion
         color = age,       # mapeie a cor segundo a idade

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +         size = age))+      # mapeie o tamanho segundo a iddade
```suggestion
         size = age))+      # mapeie o tamanho segundo a idade

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +    alpha = 0.3)            # tranparência do ponto a 30%
```suggestion
    alpha = 0.3)            # transparência do ponto a 30%

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +Torna-se importante acompanhar as camadas e a *aesthetics* de seus lotes ao fazer lotes mais complexos - por exemplo, lotes com múltiplos *geoms*. No exemplo abaixo, a aesthetic `size = ` eé atribuíd
```suggestion
Torna-se importante acompanhar as camadas e a *aesthetics* de seus gráficos à medida que vão ficando mais complexos - por exemplo, gráficos com múltiplos *geoms*. No exemplo abaixo, a aesthetic `size = ` é atribuída duas vezes - uma para `geom_point()` e outra para `geom_smooth()` - ambas as vezes como um valor estático.   

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +  geom_smooth(                  # adiciona uma linha de tendencia
```suggestion
  geom_smooth(                  # adiciona uma linha de tendência 

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +    size = 2)                   # tmanho (grossura da linha) de 2
```suggestion
    size = 2)                   # tamanho (grossura da linha) de 2

```

2022-05-09 01:17 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +### Onde incluir os atributos de mapeamento {#ggplot_basics_map_loc .unnumbered}
Parei aqui... 😄

2022-06-10 22:05 UTC, cmusso86 commented on new_pages/basics.Rmd
> +**Primeiramente, abra o RStudio.** Como os ícones deles podem ser muito parecidos, certifique-se de que você está abrindo *RStudio* e não R.
```suggestion
**Primeiramente, abra o RStudio.** Como os ícones deles podem ser muito parecidos, certifique-se de que você está abrindo mesmo  o *RStudio* e não R.
```

2022-06-10 22:10 UTC, cmusso86 commented on new_pages/basics.Rmd
> +**Primeiramente, abra o RStudio.** Como os ícones deles podem ser muito parecidos, certifique-se de que você está abrindo mesmo  o *RStudio* e não R.
```suggestion
**Primeiramente, abra o RStudio.** Como os ícones deles podem ser muito parecidos, certifique-se de que você está abrindo mesmo o *RStudio* e não R.
```

2022-06-10 22:13 UTC, cmusso86 commented on new_pages/cleaning.Rmd
> +### Funções essenciais {.unnumbered}
```suggestion
### Funções essenciais  {.unnumbered}
```

2022-06-10 22:22 UTC, cmusso86 commented on new_pages/cleaning.Rmd
> +Neste manual, referimos geralmente "colunas" e "linhas" em vez de "variáveis" e "observações". Como explicado neste manual sobre ["dados arrumados"](https://tidyr.tidyverse.org/articles/tidy-data.htm
```suggestion
Neste manual, referimos geralmente como "colunas" e "linhas" em vez de "variáveis" e "observações". Como explicado neste manual sobre ["dados arrumados"](https://tidyr.tidyverse.org/articles/tidy-data.html), a maioria dos conjuntos de dados estatísticos epidemiológicos consistem estruturalmente em linhas, colunas e valores.
```

2022-06-10 22:38 UTC, cmusso86 reviewed
kln

2022-06-10 22:38 UTC, cmusso86 commented on new_pages/basics.Rmd
> +O Console R, ou simplesmente Console, é por padrão o painel esquerdo ou inferior esquerdo do RStudio. Ele é a casa do "motor" R. É aqui que os comandos são realmente executados e as saídas não gráfic
```suggestion
O Console R, ou simplesmente Console, é por padrão o painel esquerdo ou inferior esquerdo do RStudio. Ele é a casa do "motor" de R. É aqui que os comandos são realmente executados e as saídas não gráficas e as mensagens de erro/aviso aparecem. Você pode digitar e executar comandos diretamente no Console, mas perceba que estes comandos não são salvos como são ao executar comandos de um script.
```

2022-06-10 22:38 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +# O básico o ggplot{}
```suggestion
# O básico do ggplot{}

```

2022-06-10 22:42 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +Isto é feito adicionando camadas "geoms" ao comando inicial `ggplot()`. Há muitas funções do **ggplot2**  que criam "geoms". Cada uma destas funções começa com "geom_", portanto, vamos nos referir a
Acho que vou deixar ventiladores nesse aqui mesmo... q achei mais adequado. @halian-vilela

2022-06-10 22:47 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +### Onde incluir os atributos de mapeamento {#ggplot_basics_map_loc .unnumbered}
Top, assim q eu terminar de revisar o de limpeza  de dados eu posso continuar aqui tb

2022-06-11 16:04 UTC, halian-vilela requested changes

2022-06-11 16:04 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +    title = "Distribioção de idade e peso",
```suggestion
    title = "Distribuição de idade e peso",

```

2022-06-11 16:04 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +Observe como na atribuição do título utilizamos `str_glue()` do pacote **stringr** para implantar código R dinâmico dentro do texto da string. O legenda mostrará os "Dados a partir de": "data que ref
```suggestion
Observe como na atribuição do título utilizamos `str_glue()` do pacote **stringr** para implantar código R dinâmico dentro do texto da string. O legenda mostrará os "Dados a partir de": "data que reflete a data máxima de hospitalização na linelist". Leia mais sobre isto na página em [Caracteres e strings].  

```

2022-06-11 16:04 UTC, halian-vilela commented on new_pages/ggplot_basics.Rmd
> +## Temas  {#ggplot_basics_themes}
**Parei aqui.** 🕜

2022-06-11 16:30 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +  labs(                                         #adicione rótulos, título, etc.
essa foi a correção mais importante @halian-vilela

2022-06-11 16:34 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +*Adicionar um [*tema completo*](https://ggplot2.tidyverse.org/reference/ggtheme.html) `theme_()`função para fazer ajustes de varredura - estes incluem `theme_classic()`, `theme_minimal()`, `theme_esc
```suggestion
*Adicionar um [*tema completo*](https://ggplot2.tidyverse.org/reference/ggtheme.html) `theme_()`função para fazer ajustes de varredura - estes incluem `theme_classic()`, `theme_minimal()`, `theme_dark()`, `theme_light()`theme_grey()`, `theme_bw()` entre outros  

```

2022-06-11 20:27 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +  labs(                                         #adicione rótulos, título, etc.
^^' hehehe

2022-06-13 16:54 UTC, cmusso86 commented on new_pages/basics.Rmd
> +####Sua biblioteca {.unnumbered}
```suggestion
#### Sua biblioteca {.unnumbered}
```

2022-06-13 16:56 UTC, cmusso86 commented on new_pages/basics.Rmd
> +*Nos tempos mais antigos, o arquivo acima era dividido em dois arquivos (`ui.R` e `server.R`)*
```suggestion
*Nos tempos mais antigos, o arquivo acima era dividido em dois arquivos (`ui.R`  e `server.R`)*
```

2022-06-13 16:57 UTC, cmusso86 commented on new_pages/basics.Rmd
> +1) Uma interface de usuário (ui)
```suggestion
1) Uma interface de usuário (ui)  \
```

2022-06-13 16:57 UTC, cmusso86 commented on new_pages/basics.Rmd
> +2) Uma função de servidor
```suggestion
2) Uma função de servidor  \
```

2022-06-13 17:03 UTC, cmusso86 commented on new_pages/basics.Rmd
> +### Estruture de um objeto {.unnumbered}
```suggestion
### Estrutura de um objeto {.unnumbered}
```

2022-06-13 17:04 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| Date       | **Uma vez que o R é informado que um certo grupo de dados corresponde a Data**, esses valores só podem ser apresentados e manipulados de algumas maneiras especiais. Veja a página sobre
```suggestion
| Date       | **Uma vez que o R é informado que um certo grupo de dados corresponde a Data**, esses valores só podem ser apresentados e manipulados de algumas maneiras especiais. Veja a página sobre [Trabalhando com datas] para mais informações                 | 2018-04-12 ou 15/3/1954 ou Qua 4 Jan 1980                                                             |
```

2022-06-13 17:06 UTC, cmusso86 commented on new_pages/basics.Rmd
>  | data.frame | A data frame is how R stores a **typical dataset**. It consists of vectors (columns) of data bound together, that all have the same number of observations (rows).
```suggestion
| data.frame | Uma data frame é como o R armazena uma **base de dados típica**. Consiste de vetores (volunas) de dados colocados juntas, que tês o mesmo número de observações. | O exemplo da base de dados AJS nomeado  `linelist_raw` contém 68 variáveis com 300 observações (linhas) cada. |
```

2022-06-13 17:07 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| tibble     | tibble é uma variação do data frame, a principal diferença operacional é que eles imprimem mais bem no console (exibem as primeiras 10 linhas e apenas as colunas que cabem na tela)| Qu
```suggestion
| tibble     | tibble é uma variação do data frame, a principal diferença operacional é que eles printam melhor no console (exibem as primeiras 10 linhas e apenas as colunas que cabem na tela)| Qualquer data frame, lista ou matriz pode ser convertido em um tibble com `as_tibble()`  |
```

2022-06-13 17:07 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| list       | Uma lista é como um vetor, mas contém outros objetos que podem ser outras classes diferentes| Uma lista pode conter um único número, um dataframe, um vetor e até outra lista dentro del
```suggestion
| list       | Uma lista é como um vetor, mas contém outros objetos que podem ser de outras classes diferentes| Uma lista pode conter um único número, um dataframe, um vetor e até outra lista dentro dele!    |
```

2022-06-13 17:08 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| Funço        | Ação                                                                                |
```suggestion
| Função        | Ação                                                                                |
```

2022-06-13 17:09 UTC, cmusso86 commented on new_pages/basics.Rmd
> +**Uma coluna em um quadro de dados é tecnicamente um "vetor" (ver tabela acima)** - uma série de valores que devem ser todos da mesma classe (tanto caracter, numérico, lógico, etc.).
```suggestion
**Uma coluna em um dataframe é tecnicamente um "vetor" (ver tabela acima)** - uma série de valores que devem ser todos da mesma classe (tanto caracter, numérico, lógico, etc.).
```

2022-06-13 17:12 UTC, cmusso86 commented on new_pages/basics.Rmd
>  | If the value in `rdt_result` is NOT "Positive" AND the value in `other_cases_in_home` is "Yes" | "Probable"                                 |
```suggestion
| Se o valor em  `rdt_result` NÃO for "Positivo" E o valor em `other_cases_in_home` for "Yes" | "Probable"                                 |
```

2022-06-13 17:13 UTC, cmusso86 commented on new_pages/basics.Rmd
> +###Valores faltantes {.unnumbered}
```suggestion
### Valores faltantes {.unnumbered}
```

2022-06-13 17:14 UTC, cmusso86 commented on new_pages/basics.Rmd
> +Leia mais sobre valores ausentes, infinitos, `NULL` e impossíveis na página em [Valores faltantes]. Saiba como converter valores ausentes ao importar dados na página em [Importação e exportação].
```suggestion
Leia mais sobre valores ausentes, infinitos, `NULL` e impossíveis na página em [Campos em branco/faltantes]. Saiba como converter valores ausentes ao importar dados na página em [Importação e exportação].
```

2022-06-13 17:14 UTC, cmusso86 commented on new_pages/basics.Rmd
> +### Matemática and estatística {.unnumbered}
```suggestion
### Matemática e estatística {.unnumbered}
```

2022-06-13 17:14 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| Propósit            | Exemplo no R |
```suggestion
| Propósito            | Exemplo no R |
```

2022-06-13 17:14 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| divisão  b          | 30 / 5       |
```suggestion
| divisão             | 30 / 5       |
```

2022-06-13 17:15 UTC, cmusso86 commented on new_pages/basics.Rmd
> +| ObjetiVO                   | Função             |
```suggestion
| Objetivo                  | Função             |
```

2022-06-13 17:16 UTC, cmusso86 commented on new_pages/basics.Rmd
> +[***PERIGO:*** `round()` usa "arredondamento do banqueiro" que arredonda de .5 somente se o número superior for par. Use `round_half_up()` do **zelador** para arredondar consistentemente metades para
```suggestion
[***PERIGO:*** `round()` usa "arredondamento do banqueiro" que arredonda de .5 somente se o número superior for par. Use `round_half_up()` do **janitor** para arredondar consistentemente metades para o número inteiro mais próximo. Veja [esta explicação](https://cran.r-project.org/web/packages/janitor/vignettes/janitor.html#explore-records-with-duplicated-values-for-specific-combinations-of-variables-with-get_dupes)]{style="color: red;"}
```

2022-06-13 17:21 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +    plot.subtitle = element_text(face = "italic"), # italicize subtitle
```suggestion
    plot.subtitle = element_text(face = "italic"), # deixa subtítulo em itálico

```

2022-06-13 17:23 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +`axis.text.x = element_text()`     |Axis text x-axis only (use `.y` para apenas eixo Y)
```suggestion
`axis.text.x = element_text()`     | Texto do eixo x (use `.y` para apenas eixo Y)  

```

2022-06-13 17:24 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +Os *pipes* que passam o conjunto de dados de função para função passarão a ser um símbolo de mais `+` assim que a função `ggplot()` for chamada. Observe que, neste caso, não há necessidade de especif
```suggestion
Os *pipes* que passam o conjunto de dados de função para função passarão a ser um símbolo de mais `+` assim que a função `ggplot()` for chamada. Observe que, neste caso, não há necessidade de especificar o argumento `data = ` (data), pois este é automaticamente definido como o conjunto de dados que vinha sendo usado no *pipe*.  

```

2022-06-13 17:25 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +Ao longo desta página, você já viu muitos exemplos de plotagem de dados contínuos. Aqui nós os consolidamos brevemente e apresentamos algumas variações.
```suggestion
Ao longo desta página, você já viu muitos exemplos de gráficos de dados contínuos. Aqui nós os consolidamos brevemente e apresentamos algumas variações.  

```

2022-06-13 17:35 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +Below is code for creating **violin plots** (`geom_violin`) and **jitter plots** (`geom_jitter`) to show distributions. You can specify that the fill or color is also determined by the data, by inser
```suggestion
Abaixo está o código para criar **gráficos de violino** (`geom_violin`) e **gráficos jitter** (`geom_jitter`) para mostrar as distribuições. Você pode especificar que o preenchimento ou a cor também são determinados pelos dados, inserindo estas opções dentro de `aes()`.. 

```

2022-06-13 17:36 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +# A) Jitter plot por grupo
```suggestion
# A) Gráfico de jitter por grupo

```

2022-06-13 17:38 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +  count(hospital, outcome) %>%  # abtem contagens para hospital e desfecho
```suggestion
  count(hospital, outcome) %>%  # obtém contagens para hospital e desfecho 

```

2022-06-13 17:38 UTC, cmusso86 commented on new_pages/ggplot_basics.Rmd
> +  mutate(proportion = n/sum(n)*100) # Calcule as proporções
```suggestion
  mutate(proportion = n/sum(n)*100) # Calcula as proporções

```

2022-06-13 17:40 UTC, merged